### PR TITLE
Add Axis2d.intersectionPoint, Axis2d.fromLineSegment, and QuadraticSpline2d.nearestPoint

### PR DESCRIPTION
**Pull request by MartinSStewart**
I've added `Axis2d.intersectionPoint`, `Axis2d.fromLineSegment`, and `QuadraticSpline2d.nearestPoint`. I've only written tests for `Axis2d.intersectionPoint`. I don't think `Axis2d.fromLineSegment` needs any.  `QuadraticSpline2d.nearestPoint` definately does but I ran out of energy before I got that far 😅.

### CODE REVIEW

**Comment by yourSenchou** [comment]
The `Axis2d.intersectionPoint` is something I would like to use for my project. How might I be able to help this PR along?

**Comment by MartinSStewart** [comment]
If you'd like to help this PR along then `QuadraticSpline2d.nearestPoint` still needs some tests to make sure it works correctly. If you just want `Axis2d.intersectionPoint` then I recommend just copy pasting that code into your project for now.

**Comment by ianmackenzie** [comment]
OK I think everything in this MR has been merged in, one way or another:

- I added `Axis2d.fromLineSegment` as `LineSegment2d.axis` (seemed consistent with `LineSegment2d.direction`)
- I added `Axis2d.intersectionPoint` although with a different implementation (when I tried adding some fuzz testing for the implementation in this MR it seemed to have some numerical stability issues, possibly for nearly-vertical axes?)
- I've moved `QuadraticSpline2d.nearestPoint` into the `quadraticspline2d-nearestpoint` branch of https://github.com/ianmackenzie/elm-geometry-extra, although when I added a simple test for it I got a bunch of failures so those will need investigating

So I think this MR can now be closed - @MartinSStewart  sound good?

**Comment by ianmackenzie** [comment]
...I'm an idiot, the test I added was dumb and didn't consider the case that the nearest point on the spline might be an endpoint! I'll try a better version and see what happens.

**Comment by MartinSStewart** [comment]
Sound good! Though I guess this PR will stay open until new tests are made for `QuadraticSpline2d.nearestPoint`?

**Comment by ianmackenzie** [comment]
OK just [fixed the test](https://github.com/ianmackenzie/elm-geometry-extra/commit/200bcb71d3fbf8a663012d39d28f9b0568ed4172) for `QuadraticSpline2d.nearestPoint` and everything seems good now, so I think we can close this MR :slightly_smiling_face:

**Pull request closed without merging**
