### PR TITLE
Polyline{2,3}d centroid function

### PR DESCRIPTION
**Pull request by davcamer**
The implementation uses the approach suggested by Ian on the original
issue:
https://github.com/ianmackenzie/elm-geometry/issues/64

Here is his description:
For polylines, the simplest implementation would basically be to add
up weighted line segment centroid coordinates and then divide by total
weight at the end, but this would encounter roundoff issues if the
coordinates were large (the polyline was far from the origin). A better
approach would be:

* Find the rough centroid by getting the centroid of the polyline's
  bounding box
* Add up the vectors from that approximate centroid to each line segment's
  centroid, weighted by line segment length
* Divide the vector sum by overall weight, then add to the initial
  approximate centroid

Pull request checklist:

  - Is the pull request from a dedicated branch in your fork instead of
    `master`? (Preferred, but not mandatory.)
  - Have you added yourself to the AUTHORS file? Not mandatory if you'd prefer
    to stay anonymous, but don't be shy!
  - Is "Allow edits from maintainers" enabled? (There should be a checkbox for
    this when you open the pull request.)
  - Is the code formatted using the same version of `elm-format` as the rest of
    `elm-geometry`? (If running `elm-format` doesn't change any existing code,
    then the answer is probably 'yes'.)
  - Is code (mostly) wrapped to 80 columns? (It's OK if type annotations and
    occasional things like string literals are longer.)
  - BONUS POINTS: Have you added tests for new functionality?
  - EXTRA BONUS POINTS: Have you added documentation for new functionality?
    (Don't worry too much about documentation text - I like that to have a
    consistent style, which means writing most of it myself - but if you can
    come up with some code examples to use in documentation that would be
    fantastic.)

Don't worry too much if you're not sure if one of the above is true, or if you
know it's not true but aren't sure how to fix it - just go ahead and open the
pull request and we'll sort it out. The intent is for this list to be helpful,
not intimidating!

### CODE REVIEW

**Comment by davcamer** [comment]
I noticed there is a `Polygon2d.triangulate` method. Are you suggesting calculating triangles from the bounding box center because it will be more performant than triangulating via `TriangularMesh`?

**Comment by ianmackenzie** [comment]
Yeah, `Polygon2d.triangulate` is very complex internally (necessarily so!), so won't be nearly as efficient as the approach using signed areas. Check out [Polygon2d/Monotone.elm](https://github.com/ianmackenzie/elm-geometry/blob/master/src/Polygon2d/Monotone.elm) if you want to see what happens when you take a complex geometric algorithm designed for imperative code with arrays and pointers and translate it into Elm =)

Just looking through the updated code now...

**Comment by ianmackenzie** [comment]
Oh btw, thanks for catching the `examplePolyline` 2D/3D typo in `Polyline3d.elm` =)

**Comment by ianmackenzie** [comment]
One super minor nit (I'd just make the change myself, but I'm on the bus with my phone): can you change `\_ ->` to `\() ->` in the various `Test.test` tests? The former accepts any argument, while the latter only accepts the unit value `()`. This means it conveys a bit more information when read, and adds a bit of type safety - if `Test.test` changes in the future to pass a useful argument to the lambda, then you'll get a compile error instead of the lambda accepting the new argument and then silently ignoring it.

**Comment by ianmackenzie** [comment]
I think everything else looks good! Once the tiny lambda change is in, do you think this is ready to merge?

**Comment by davcamer** [comment]
Interesting point about the params for the test function. A co-worker and I had been talking about this a few days earlier and hadn't come up with a reason to prefer one over the other, but I like your point about future changes. Cheers!

I think it is ready to merge now. I'll do the Polygon centroids on another branch.

**Comment by ianmackenzie** [comment]
Great, thanks! The type safety with `\() ->` is definitely nice, but if you ask me, the "extra information when read" aspect is even more important. If I see `\() ->` when reading a code base then I immediately know that it's being used for lazy evaluation of some sort, while `\_ ->` could also mean that there's an ignored argument and I'd have to look closer to see. (When I was reviewing your changes I actually did end up checking the `elm-test` documentation quickly to verify that it wasn't passing anything useful to the actual test function.)

**Pull request merged**
