### PR TITLE
scaleTo methods for Vector2d and Vector3d

### PR DESCRIPTION
**Pull request by g-belmonte**
Pull request related to https://github.com/ianmackenzie/elm-geometry/issues/134

Pull request checklist:

  - [x] Is the pull request from a dedicated branch in your fork instead of
    `master`?
  - [x] Have you added yourself to the AUTHORS file?
  - [x] Is "Allow edits from maintainers" enabled?
  - [x] Is the code formatted using the same version of `elm-format` as the rest of
    `elm-geometry`?
  - [x] Is code (mostly) wrapped to 80 columns?
  - [x] BONUS POINTS: Have you added tests for new functionality?
  - [x] EXTRA BONUS POINTS: Have you added documentation for new functionality?

@ianmackenzie let me know what you think! :)

### CODE REVIEW

**Comment by ianmackenzie** [comment]
Looking good, thanks for adding docs/tests! A few requests:

  - Can you try implementing `scaleTo` similar to the old `normalize`? For performance reasons I'd like to avoid the intermediate `Maybe` (extra memory allocation) if possible. I think this will involve adding something like `scaleFactor = givenLength / scaledLength` to the existing `normalize` logic and then use `x = scaleFactor * scaledX` instead of `x = scaledX / scaledLength`.
  - I think those tests would fail if the fuzzer produced a zero vector (which you can probably test by increasing the number of fuzz tests that get run, e.g. `elm-test --fuzz 5000`). I think there should probably be some logic in both the `scaleTo` and `normalize` tests that first checks if the fuzzed `vector` is equal to `Vector2d.zero`/`Vector3d.zero` and if so checks that the scaled vector is also equal to the zero vector; otherwise use the existing logic.
  - Very minor point but I think the tests would be slightly cleaner if you used `Test.fuzz2` instead of `Test.fuzz` with `Fuzz.tuple`.

**Comment by g-belmonte** [comment]
I did some changes to the `scaleTo`, then I ran `elm-test --fuzz 5000`. This is what I got:

image

Is it something to worry about?

**Comment by ianmackenzie** [comment]
Yeah, don't worry about that test failure, I think I just set it up in a way that you occasionally have really numerically bad situations (like an axis that's _almost_ parallel to the plane) where it's impossible to get super high accuracy no matter what you do. I do have to fix that test to avoid those cases (while being careful not to filter out _actual_ problems), but it's certainly not related to anything you're doing!

**Comment by ianmackenzie** [comment]
By the way, any chance you could tweak the `Vector3d` example to be a bit more like the `Vector2d` one? (Nicer numbers, output is formatted as an expression you could actually write instead of what the REPL would show, etc.) You can 'cheat' a bit here and basically use the same 2D example by just (for example) setting the Y component to zero in the 3D case.

**Comment by ianmackenzie** [comment]
For the tests, it's certainly good to have some explicit tests for the zero vector case, but I think there still needs to be something in the general case to handle the situation where the fuzzer produces a zero vector (I may not have explained this well). For example, taking `normalize` as an example because it's a bit simpler,

```elm
\vector ->
    Vector3d.normalize vector
        |> Vector3d.length
        |> Expect.quantity (Quantity.float 1)
```

will fail if `vector` happens to be `Vector3d.zero` since then the length will be zero, not one! I think you'll need something like

```elm

\vector ->
    if vector == Vector3d.zero then
        Vector3d.normalize vector
            |> Expect.equal Vector3d.zero
    
    else
        Vector3d.normalize vector
            |> Vector3d.length
            |> Expect.quantity (Quantity.float 1)
```

**Comment by ianmackenzie** [comment]
Oh, and I appreciate the attempt to simplify/clean up the old implementation of `normalize`, but there's actually a reason for the weird logic with `largestComponent` 🙂. _Mathematically_ your version is the same (and simpler), but _numerically_ calculations like `x * x` can underflow or overflow with very small or very large `Float` values (see https://github.com/ianmackenzie/elm-geometry/issues/99 for a detailed discussion). Dividing everything by the largest component (and then effectively multiplying by that again afterwards, after doing the square/square root) avoids both issues.

**Comment by g-belmonte** [comment]
I'm ashamed by the looks of that bad 3d vector example :joy: For the Vector2d I used Pythagorean triplets, so that I could have nice looking numbers... but I had no idea of an example like that on a 3d vector :sweat_smile: I'll put one of the components as zero for now

Now I see the problems with the tests and the implementation I did :smile: Let me fix that :)

**Comment by ianmackenzie** [comment]
I think this is looking great now! Was there anything else you were thinking of adding or are you OK to have this merged?

**Comment by g-belmonte** [comment]
I think this is it, at least for this one :grin:

**Pull request merged**
